name: on-prem-release

#on:
#  push:
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+'

on:
  push:
    tags:
      - 'v*'


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: publish
        run: |
          echo "publish"
