name: release-please
on:
  push:
    branches:
      - master
#on:
#  pull_request:
#    branches:
#      - master
#    types: [closed]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          default-branch: master
